#pragma once
#include "pch.h"


/*
Generates a kkt matrix structured like one generated by assets collocation schemes

nx: number of state variables >0
nu: number of control variables >=0
cardstates: number of cardinal states per defect constraint >=2
numsegs: number of defect constraint segments

returns upper triangular row major sparse matrix
*/
Eigen::SparseMatrix<double, Eigen::RowMajor> collocation_kkt_matrix(int nx, int nu, int cardstates, int numsegs);